version: "3"
services:
  circle-system:
    image: circle-system
    build: .
    command: npm run start:dev
    ports:
      - "3000:3000"
      - "3001:3001"
    expose: 3000
    environment:
      - NODE_ENV=production
      - DB_HOST=${PRODUCTION_DB_HOST}
      - DB_USER=${PRODUCTION_DB_USERNAME}
      - DB_PASSWORD=${PRODUCTION_DB_PASSWORD}
      - DB_DATABASE=${PRODUCTION_DB_NAME}