version: "3.8"

networks:
    app-network:
        driver: bridge

services:
    backend:
        container_name: circle-system-01
        build:
            context: .
            dockerfile: Dockerfile
            target: production
        expose:
            - "3000"
        env_file:
            - .env
        environment:
            - PORT=3000
            - NODE_ENV=production
        networks:
            - app-network
        deploy:
            resources:
                limits:
                    cpus: "0.5" # Limita o container a usar no máximo 50% de uma CPU
                    memory: "0.5GB" # Limita o uso de memória do container para 512 MB
        command: npm start

    nginx:
        image: nginx:latest
        container_name: nginx-proxy
        depends_on:
            - backend
        ports:
            - "80:80" # Porta pública HTTP
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf:ro # Configuração do Nginx

    networks:
        app-network:
            driver: bridge
