version: "3.8"
services:
    api-instance-01:
        container_name: circle-system-01
        build:
            context: .
            dockerfile: Dockerfile
            target: production
        expose:
            - "3000"
        environment:
            - PORT=3000
            - NODE_ENV=production

    api-instance-02:
        container_name: circle-system-02
        build:
            context: .
            dockerfile: Dockerfile
            target: production
        expose:
            - "3000"
        environment:
            - PORT=3000
            - NODE_ENV=production

    api-instance-03:
        container_name: circle-system-03
        build:
            context: .
            dockerfile: Dockerfile
            target: production
        expose:
            - "3000"
        environment:
            - PORT=3000
            - NODE_ENV=production
    nginx:
        image: nginx:latest
        container_name: nginx-proxy
        ports:
            - "80:80" # Porta pública HTTP
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf:ro # Configuração do Nginx
