version: "3.8"

networks:
    app-network:
        driver: bridge

services:
    backend:
        container_name: circle-system-01
        build:
            context: .
            dockerfile: Dockerfile
            target: production
        expose:
            - "3000"
        env_file:
            - .env
        environment:
            - PORT=3000
            - RUN_SCRIPTS_MODE=false
            - NODE_ENV=production
            - CIRCLE_SWIPE_ENGINE_API=http://localhost:5000/
        networks:
            - app-network
        deploy:
            resources:
                limits:
                    cpus: "0.5" # Limita o container a usar no máximo 50% de uma CPU
                    memory: "0.5GB" # Limita o uso de memória do container para 512 MB
        volumes:
            - ./firebase-settings.json:/app/firebase-settings.json # Copia o arquivo do host para o container
        healthcheck: # 🩺 Garante que o container está pronto antes de o Nginx tentar acessá-lo
            test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
            interval: 10s
            retries: 3
            start_period: 5s
            timeout: 5s
    nginx:
        image: nginx:latest
        container_name: nginx-proxy
        depends_on:
            backend:
                condition: service_healthy # ✅ Agora o Nginx só sobe quando o backend estiver pronto
        ports:
            - "80:80" # Porta pública HTTP
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf:ro # Configuração do Nginx

    networks:
        app-network:
            driver: bridge
