name: Push-to-EC2
on:
    push:
        branches:
            - main

jobs:
    build:
        name: Build Docker Image
        runs-on: ubuntu-latest

        steps:
            - name: Checkout Source
              uses: actions/checkout@v3

            - name: Login to Docker Hub
              run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

            - name: Build Docker Image
              run: docker build --target build -t tiagosavioli/circle-system:latest .

            - name: Publish Image to Docker Hub
              run: docker push tiagosavioli/circle-system:latest

    deploy:
        name: Deploy to EC2
        needs: build
        runs-on: ubuntu-latest

        steps:
            - name: Pull Image from Docker Hub
              run: docker pull tiagosavioli/circle-system:latest

            - name: Delete Old Container
              run: docker rm -f circle-system-container || true

            - name: Run Docker Container
              run: docker run -d -p 3000:3000 --name circle-system-container tiagosavioli/circle-system:latest
